### ISSUE TITLE
Naming convention option not working

### ISSUE THREAD

**Issue by edullavin** [here-erhe/Design-Token-Exporter#1]
Hi! This is a great plugin, but when I try to export out styles, it always uses camel case naming convention regardless of what I other options I choose.

**Comment by here-erhe** [comment]
Hi and nice to hear that. How your Sketch layers are named which you try export? Which export setting you use?

**Comment by edullavin** [comment]
![Screen Shot 2019-07-02 at 10 59 23 AM](https://user-images.githubusercontent.com/10850344/60523301-7c030900-9cb8-11e9-9c92-74587402ac08.png)

I have attached a screen shot.
Sketch file showing a light green box with a layer style called "OK".
Green box layer is labeled $color-msg-ok
In VS code editor, SCSS output is camel case.

![Screen Shot 2019-07-02 at 11 01 28 AM](https://user-images.githubusercontent.com/10850344/60523474-c8e6df80-9cb8-11e9-92df-ce97e771f4f1.png)

Second screenshot shows options that were chosen for export.

Hope this helps!

**Comment by here-erhe** [comment]
Screenshots helped a lot. Thanks. I just released new version which fix naming problem.

**Comment by edullavin** [comment]
Almost there! If my layer name includes -, it'll output perfectly (even accounts for the $ and only adds one). There is another bug though and I have taken another screenshot for you. I wish I could help with the code and do a pull request, but I don't have the skill to do so.

What I am seeing now is that the function to kebab case is missing the - for names using spaces.
The layer name is "Enabled Copy" and the screenshot below shows the output options for it.

![Screen Shot 2019-07-03 at 2 55 05 PM](https://user-images.githubusercontent.com/10850344/60617999-f7d98000-9da2-11e9-89b8-45d8974dbb5e.png)

**Comment by here-erhe** [comment]
I released new version which can handle layer names which contains spaces.

**Comment by edullavin** [comment]
Works like a charm! Thank you for creating such a great plug-in. If I run into any more issues I'll let you know, but great job.
