### ISSUE TITLE
Export Tokens returns "Select layers or artboards"

### ISSUE THREAD

**Issue by zdanislaw** [here-erhe/Design-Token-Exporter#3]
Hi guys, I really like the plugin and this is something I was looking for. 
However I cannot use on e of the option: Export Tokens.
Whatever I try always returns:

![image](https://user-images.githubusercontent.com/8605219/78508045-3d890600-7784-11ea-8ccc-6e3ae88c5615.png)

Other options work fine.

Operating system: Mojave
Sketch: 64

**Comment by McSam27** [comment]
I also have this issue.
Design Token Exporter: 1.0.1
OS: Mojave 10.14.6
Sketch: 64 (93537)

**Comment by here-erhe** [comment]
Nice to hear that you like the plugin. Can you send screen capture where I can see your layers names which you try export?

**Comment by McSam27** [comment]
I was using my old naming convention but it looks like if I swap follow your gif on the README, it starts to work fine.

Is there an example project? I think that would benefit users who are learning how to use the plugin.

**Comment by here-erhe** [comment]
Yeah, naming have to follow pattern like type/category/tokenname (e.g. color/background-color/bg-light). You find whole list of types and categories in readme. 

Example project is on the roadmap but I haven't found to time to do it yet. But definitely I will do it.

**Comment by McSam27** [comment]
Awesome, much appreciated. I've been working on my own, trying to document the findings I have so far. Would love your expertise in the example project though haha!

**Comment by here-erhe** [comment]
Project is not maintained anymore
