### ISSUE TITLE
Add example project or documentation on naming standards

### ISSUE THREAD

**Issue by McSam27** [here-erhe/Design-Token-Exporter#4]
After researching this tool in-depth for a while now, the naming standards of each token category are not defined. 
Without the naming standard, it forces consumers to dig through the source code to understand how to set up their Sketch project. 
If a layer is not named correctly, the plugin seems to throw an error and does not perform the export.

An extra column could be added to the table in the `README.md` file and showcase an example of how to name the Sketch layers.

I would also be open to help contribute to the project, not sure if there are any guidelines defined anywhere. 

Thanks for such an awesome tool!

**Comment by McSam27** [comment]
Any updates on this?

**Comment by here-erhe** [comment]
Project is not maintained anymore
